# Generated by Django 6.0.4 on 2026-06-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_alerta', models.CharField(choices=[('HUMEDAD_BAJA', 'Humedad baja'), ('BATERIA_BAJA', 'Batería baja'), ('SIN_CONEXION', 'Sin conexión'), ('ERROR_BOMBA', 'Error de bomba'), ('GENERAL', 'General')], max_length=20)),
                ('nivel', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICA', 'Crítica')], max_length=20)),
                ('mensaje', models.CharField(max_length=255)),
                ('atendida', models.BooleanField(default=False)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alerta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaSistema',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=120)),
                ('tabla_afectada', models.CharField(blank=True, max_length=120, null=True)),
                ('id_registro_afectado', models.IntegerField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Auditoría del sistema',
                'verbose_name_plural': 'Auditoría del sistema',
                'db_table': 'auditoria_sistema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bateria',
            fields=[
                ('id_bateria', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=60, null=True)),
                ('capacidad_mah', models.IntegerField(blank=True, null=True)),
                ('voltaje_nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(choices=[('BUENA', 'Buena'), ('MEDIA', 'Media'), ('BAJA', 'Baja'), ('CRITICA', 'Crítica')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Batería',
                'verbose_name_plural': 'Baterías',
                'db_table': 'bateria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BombaAgua',
            fields=[
                ('id_bomba', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('caudal_litros_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_actual', models.CharField(choices=[('ENCENDIDA', 'Encendida'), ('APAGADA', 'Apagada'), ('MANTENIMIENTO', 'Mantenimiento')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bomba de agua',
                'verbose_name_plural': 'Bombas de agua',
                'db_table': 'bomba_agua',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComandoRemoto',
            fields=[
                ('id_comando', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('ENCENDER', 'Encender'), ('APAGAR', 'Apagar'), ('REINICIAR', 'Reiniciar'), ('ACTUALIZAR_CONFIG', 'Actualizar config')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('EJECUTADO', 'Ejecutado'), ('FALLIDO', 'Fallido')], max_length=20)),
                ('parametros_texto', models.TextField(blank=True, null=True)),
                ('fecha_hora_envio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Comando remoto',
                'verbose_name_plural': 'Comandos remotos',
                'db_table': 'comando_remoto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionRiego',
            fields=[
                ('id_configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('umbral_humedad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tiempo_riego_segundos', models.IntegerField()),
                ('modo_riego', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático')], max_length=20)),
                ('intervalo_lectura_segundos', models.IntegerField()),
                ('riego_habilitado', models.BooleanField(default=True)),
                ('vigente', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración de riego',
                'verbose_name_plural': 'Configuraciones de riego',
                'db_table': 'configuracion_riego',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DispositivoIot',
            fields=[
                ('id_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('modelo', models.CharField(blank=True, max_length=80, null=True)),
                ('direccion_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'Mantenimiento')], max_length=20)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dispositivo IoT',
                'verbose_name_plural': 'Dispositivos IoT',
                'db_table': 'dispositivo_iot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoBomba',
            fields=[
                ('id_estado_bomba', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ENCENDIDA', 'Encendida'), ('APAGADA', 'Apagada')], max_length=20)),
                ('origen', models.CharField(choices=[('AUTOMATICO', 'Automático'), ('MANUAL', 'Manual'), ('WEB', 'Web'), ('ESP32', 'ESP32')], max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado de bomba',
                'verbose_name_plural': 'Estados de bomba',
                'db_table': 'estado_bomba',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoRiego',
            fields=[
                ('id_estado_riego', models.AutoField(primary_key=True, serialize=False)),
                ('estado_riego', models.CharField(choices=[('INICIADO', 'Iniciado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('FALLIDO', 'Fallido'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('duracion_segundos', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado de riego',
                'verbose_name_plural': 'Estados de riego',
                'db_table': 'estado_riego',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LecturaBateria',
            fields=[
                ('id_lectura_bateria', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('voltaje', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lectura de batería',
                'verbose_name_plural': 'Lecturas de batería',
                'db_table': 'lectura_bateria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LecturaHumedad',
            fields=[
                ('id_lectura_humedad', models.AutoField(primary_key=True, serialize=False)),
                ('valor_humedad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lectura de humedad',
                'verbose_name_plural': 'Lecturas de humedad',
                'db_table': 'lectura_humedad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id_predio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('ubicacion', models.CharField(blank=True, max_length=180, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Predio',
                'verbose_name_plural': 'Predios',
                'db_table': 'predio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RespuestaComando',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_respuesta', models.CharField(blank=True, max_length=50, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=255, null=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('fecha_hora_respuesta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Respuesta de comando',
                'verbose_name_plural': 'Respuestas de comando',
                'db_table': 'respuesta_comando',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sensor', models.CharField(choices=[('HUMEDAD', 'Humedad'), ('TEMPERATURA', 'Temperatura'), ('OTRO', 'Otro')], max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('unidad_medida', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('FALLA', 'Falla'), ('MANTENIMIENTO', 'Mantenimiento')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'db_table': 'sensor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('correo', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id_usuario_rol', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario-Rol',
                'verbose_name_plural': 'Usuarios-Roles',
                'db_table': 'usuario_rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZonaSiembra',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('cultivo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Zona de siembra',
                'verbose_name_plural': 'Zonas de siembra',
                'db_table': 'zona_siembra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelemetriaESP32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo_codigo', models.CharField(default='esp32-01', max_length=100)),
                ('humedad_suelo', models.FloatField(blank=True, null=True)),
                ('temperatura_ambiente', models.FloatField(blank=True, null=True)),
                ('humedad_ambiente', models.FloatField(blank=True, null=True)),
                ('distancia_cm', models.FloatField(blank=True, null=True)),
                ('nivel_tanque_pct', models.FloatField(blank=True, null=True)),
                ('bomba_activa', models.BooleanField(default=False)),
                ('modo', models.CharField(default='AUTO', max_length=20)),
                ('payload_raw', models.JSONField(blank=True, default=dict)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'telemetria_esp32',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
